apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: real-estate-app
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443