apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: real-estate-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/itsmanibharathi/gensparkcapstoneprojectapi:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: pfx-secret
          mountPath: /etc/pfx
          readOnly: true
        env:
        - name: SQL_SERVER_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: SQL_SERVER_CONNECTION_STRING
        - name: JWT_USER_SECRET
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: JWT_USER_SECRET
        - name: COMMUNICATION_SERVICES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: COMMUNICATION_SERVICES_CONNECTION_STRING
        - name: COMMUNICATION_SERVICES_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: COMMUNICATION_SERVICES_FROM_EMAIL
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
      volumes:
      - name: pfx-secret
        secret:
          secretName: pfx-secret
          