apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: real-estate-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

