name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/api/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push client image
      run: |
        docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository }}/api:latest . --push