name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**'
    # tags:
    #   - 'v*.*.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0  # Fetch all tags

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Extract version from Git tag'
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: 'Build and push Docker client image'
        run: |
          docker build --tag ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest ./client
          docker push ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest
          
      - name: 'Build and push Docker api image'
        run: |
          docker build --tag ghcr.io/itsmanibharathi/gensparkcapstoneprojectapi:latest ./api
          docker push ghcr.io/itsmanibharathi/gensparkcapstoneprojectapi:latest