name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0  # Fetch all tags

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      
      - name: 'Build and push Docker frontend image'
        run: |
          docker build --tag ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest ./frontend
          docker push ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest

      - name: Get the version tag
        id: get_version_tag
        run: |
            # Extract the version tag from the GITHUB_REF environment variable
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
        
      - name: Display the version tag
        run: |
            echo "Version tag: $VERSION_TAG"
  
          