name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0  # Fetch all tags

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      
      - name: 'Build and push Docker frontend image'
        run: |
          docker build --tag ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest ./frontend
          docker push ghcr.io/itsmanibharathi/gensparkcapstoneprojectfrontend:latest
  
          